# Setup
title:        Damon Hu's Blog 
tagline:      Blog for tech, life etc. 
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Damon Hu 
  url:        https://github.com/dreamhb 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-leap-day