# Setup
title:        Jayden's Blog 
tagline:      Plan-Do-Check-Action 
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Jayden 
  url:        https://github.com/dreamhb 

# Gems
plugins:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman
